# Generated by Django 2.2.16 on 2022-09-10 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20220908_1741'),
        ('users', '0004_auto_20220910_1232'),
    ]

    operations = [
    ]
